server:
  port: 8088


spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo_db
    username: root
    password: spmysql
  jpa:
    hibernate:ddl-auto: update
    generate-ddl: true
    show-sql: true
    format-sql: true